[tools]
fzf = "latest"
go = "latest"
java = "temurin-25"
lazygit = "latest"
node = "lts"
ruby = "latest"
tree-sitter = "latest"
"gem:jekyll" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"

[env]
GOPATH = "{{env.HOME}}/.cache/go"
