[tools]
"cargo:gen-license" = "latest"
"cargo:gitnr" = "latest"
"cargo:tealdeer" = "latest"
"gem:jekyll" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
fzf = "latest"
go = "latest"
java = "temurin-25"
lazygit = "latest"
navi = "latest"
node = "lts"
ruby = "latest"
rust = "stable"
tree-sitter = "latest"
yazi = "latest"

[env]
GOPATH = "{{env.HOME}}/.go"
