[tools]
go = "latest"
rust = "stable"
node = "lts"
elixir = "latest"
erlang = "latest"
java = "temurin-25"
ruby = "latest"

"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"gem:jekyll" = "latest"

tree-sitter = "latest"

difftastic = "latest"
"cargo:gen-license" = "latest"
"cargo:gitnr" = "latest"
lazydocker = "latest"
lazygit = "latest"

"cargo:tealdeer" = "latest"
navi = "latest"
fzf = "latest"
yazi = "latest"
fastfetch = "latest"

[env]
GOPATH = "{{env.HOME}}/.go"
